import { useState } from 'react'
import { ArrowRight, ArrowUpRight, BookOpen, Check, CircleCheck, Compass, GraduationCap, HeartHandshake, Menu, Sparkles, Users, X } from 'lucide-react'
import './styles.css'

const programmes = [
  { id: 'early', label: 'Early Years', title: 'A confident beginning', text: 'A warm, purposeful foundation where curiosity, play, language, and independence grow together.', icon: Sparkles, color: 'mint' },
  { id: 'primary', label: 'Primary', title: 'Discover. Question. Create.', text: 'Children build strong academic foundations while developing character, confidence, and a love of learning.', icon: BookOpen, color: 'gold' },
  { id: 'secondary', label: 'Secondary', title: 'Ready for what comes next', text: 'A focused environment for middle and teenage years, with the guidance to think deeply and act responsibly.', icon: GraduationCap, color: 'blue' },
]
const gallery = [
  { src: 'https://www.quantumleapschools.org/Image/74932520230825.jpg', label: 'Focused learning', className: 'gallery-wide' },
  { src: 'https://www.quantumleapschools.org/Image/6794720240907.jpg', label: 'School community', className: '' },
  { src: 'https://quantumleapschools.org/Image/10172920230829.jpg', label: 'Celebrating achievement', className: '' },
  { src: 'https://quantumleapschools.org/Image/13022520230825.jpg', label: 'Sport and movement', className: '' },
]
const curriculum = [
  ['01', 'Strong foundations', 'A balanced programme for early years, primary, and secondary learners.'],
  ['02', 'Nigerian curriculum', 'Learning grounded in the requirements and realities of Nigerian education.'],
  ['03', 'British curriculum pathway', 'An international perspective for families seeking broader academic preparation.'],
  ['04', 'Character and skills', 'Technology, creativity, leadership, and moral integrity alongside academics.'],
]

function Logo() { return <div className="brand"><span className="logo-orbit"><i /><i /><i /></span><span>Quantum <b>Leap</b><small> SCHOOLS</small></span></div> }

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [active, setActive] = useState('early')
  const [modal, setModal] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const programme = programmes.find(item => item.id === active)
  const openAdmissions = () => { setSubmitted(false); setModal(true) }
  const submitEnquiry = (event) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    const message = `Hello Quantum Leap Schools. I would like to make an admissions enquiry.%0A%0AParent/guardian: ${data.get('name')}%0AEmail or phone: ${data.get('contact')}%0AEnquiry: ${data.get('enquiry')}`
    window.open(`https://wa.me/2348023153950?text=${message}`, '_blank', 'noopener,noreferrer')
    setSubmitted(true)
  }

  return <div className="site">
    <div className="notice"><span><span className="notice-dot" /> Admissions enquiries are now open</span><a href="#admissions">Explore admissions <ArrowUpRight size={13} /></a></div>
    <header className="header"><nav className="nav container"><a href="#home"><Logo /></a><div className={`links ${menuOpen ? 'open' : ''}`}><a href="#about" onClick={() => setMenuOpen(false)}>Our school</a><a href="#learning" onClick={() => setMenuOpen(false)}>Learning</a><a href="#life" onClick={() => setMenuOpen(false)}>School life</a><a href="#admissions" onClick={() => setMenuOpen(false)}>Admissions</a></div><div className="nav-actions"><a className="phone" href="tel:+2348023153950">+234 802 315 3950</a><button className="button button-dark" onClick={openAdmissions}>Enquire now <ArrowRight size={15} /></button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div></nav></header>
    <main id="home">
      <section className="hero container"><div className="hero-content"><div className="kicker"><span /> Quantum Leap Schools · Ikorodu, Lagos</div><h1>A place where<br /><em>potential</em> takes flight.</h1><p>We nurture curious minds, grounded character, and the confidence to step into the world ready to make a difference.</p><div className="hero-buttons"><button className="button button-primary" onClick={openAdmissions}>Begin your journey <ArrowUpRight size={17} /></button><a className="learn-link" href="#about">Discover our story <ArrowRight size={15} /></a></div><div className="hero-note"><span className="note-icon"><HeartHandshake size={16} /></span><span>Growing learners from early childhood through the teenage years.</span></div></div><div className="hero-art"><div className="sun" /><div className="hill hill-one" /><div className="hill hill-two" /><div className="tree tree-one"><i /><i /><i /></div><div className="tree tree-two"><i /><i /><i /></div><div className="paper-plane"><ArrowUpRight /></div><div className="art-card"><span>Today’s question</span><strong>What could<br />you discover?</strong><div><span className="line" /><span className="line short" /></div></div><div className="art-label">Learning is a leap<br />worth taking.</div></div></section>
      <section className="stat-bar"><div className="container stats"><div><strong>01</strong><span>Curious minds</span></div><div><strong>02</strong><span>Strong foundations</span></div><div><strong>03</strong><span>Confident futures</span></div><div className="stat-end"><span>Ikorodu · Lagos</span><Compass size={18} /></div></div></section>
      <section className="section container about" id="about"><div className="section-intro"><div><div className="kicker"><span /> The Quantum Leap way</div><h2>Education that grows<br />with <em>the child.</em></h2></div><p>At Quantum Leap Schools, learning goes beyond textbooks. We create an environment where children are encouraged to ask questions, love learning, build integrity, and discover their own potential.</p></div><div className="values"><article><span className="value-icon mint"><HeartHandshake size={20} /></span><h3>Character first</h3><p>Kindness, honesty, responsibility, and respect are part of everyday learning.</p><a href="#learning">Our values <ArrowUpRight size={14} /></a></article><article><span className="value-icon gold"><BookOpen size={20} /></span><h3>Learning with purpose</h3><p>Solid academic foundations meet curiosity, creativity, and real-world thinking.</p><a href="#learning">Our approach <ArrowUpRight size={14} /></a></article><article><span className="value-icon blue"><Users size={20} /></span><h3>Every child seen</h3><p>Children are supported as individuals, with the guidance to grow at their own pace.</p><a href="#admissions">Meet the team <ArrowUpRight size={14} /></a></article></div></section>
      <section className="learning-section" id="learning"><div className="container learning-grid"><div className="learning-copy"><div className="kicker"><span /> Learning pathways</div><h2>Every leap begins<br />with a <em>first step.</em></h2><p>From the first questions of early childhood to the bigger decisions of adolescence, our programmes are designed to help learners move forward with confidence.</p><div className="programme-tabs">{programmes.map((item, index) => <button key={item.id} className={active === item.id ? 'active' : ''} onClick={() => setActive(item.id)}><span>0{index + 1}</span>{item.label}<ArrowRight size={14} /></button>)}</div></div><div className={`programme-card ${programme.color}`}><span className="programme-icon">{(() => { const Icon = programme.icon; return <Icon size={24} /> })()}</span><span className="programme-label">{programme.label}</span><h3>{programme.title}</h3><p>{programme.text}</p><div className="programme-checks"><span><Check size={13} /> Purposeful learning</span><span><Check size={13} /> Caring guidance</span><span><Check size={13} /> Confident growth</span></div><button className="circle-button" onClick={openAdmissions}><ArrowUpRight size={20} /></button></div></div></section>
      <section className="curriculum-section"><div className="container"><div className="section-intro compact"><div><div className="kicker"><span /> What families can expect</div><h2>A pathway built<br />around <em>possibility.</em></h2></div><p>We’ve kept the information clear for prospective families. The school can replace these overview points with the exact current subject lists, fees, and year-group requirements.</p></div><div className="curriculum-grid">{curriculum.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="curriculum-actions"><a className="outline-link" href="https://sms.quantumleapschools.org/" target="_blank" rel="noreferrer">Student / staff portal <ArrowUpRight size={15} /></a><a className="outline-link" href="https://www.google.com/maps/search/?api=1&query=6-8+Salami+Solebo+Street+Igbo+Olowo+Ikorodu+Lagos" target="_blank" rel="noreferrer">View campus on Maps <ArrowUpRight size={15} /></a></div></div></section>
      <section className="section container life" id="life"><div className="life-heading"><div><div className="kicker"><span /> More than a classroom</div><h2>A school life full<br />of <em>possibility.</em></h2></div><p>Learning happens in the classroom, on the field, in conversation, and in every new challenge a child is brave enough to try.</p></div><div className="life-grid"><div className="life-feature"><div className="feature-content"><span className="feature-number">01</span><h3>Find your spark.</h3><p>Space for learners to explore technology, creativity, leadership, sport, and the ideas that excite them.</p><a href="#admissions">See school life <ArrowUpRight size={15} /></a></div><div className="feature-orbit"><Sparkles /></div></div><div className="life-list"><div><span>02</span><div><strong>A community that cares</strong><p>Families, teachers, and learners moving forward together.</p></div><ArrowUpRight size={16} /></div><div><span>03</span><div><strong>Ready for the wider world</strong><p>Confidence, curiosity, and character for every next step.</p></div><ArrowUpRight size={16} /></div><div><span>04</span><div><strong>Day and boarding pathways</strong><p>A focused school experience built around each learner.</p></div><ArrowUpRight size={16} /></div></div></div></section>
      <section className="gallery-section"><div className="container"><div className="gallery-heading"><div><div className="kicker"><span /> Around Quantum Leap</div><h2>See the school<br /><em>in motion.</em></h2></div><a className="learn-link" href="https://www.quantumleapschools.org/gallery.aspx" target="_blank" rel="noreferrer">View the original gallery <ArrowUpRight size={15} /></a></div><div className="gallery-grid">{gallery.map(image => <a className={`gallery-image ${image.className}`} href={image.src} target="_blank" rel="noreferrer" key={image.src}><img src={image.src} alt={image.label} loading="lazy" /><span>{image.label} <ArrowUpRight size={14} /></span></a>)}</div></div></section>
      <section className="news-section"><div className="container"><div className="section-intro compact"><div><div className="kicker"><span /> From the school</div><h2>Moments worth<br /><em>sharing.</em></h2></div><a className="learn-link" href="https://www.quantumleapschools.org/news.aspx" target="_blank" rel="noreferrer">Read school news <ArrowUpRight size={15} /></a></div><div className="news-grid"><article><span>School life</span><h3>Learning beyond the classroom</h3><p>Explore the school’s public updates, activities, and community moments.</p><a href="https://www.quantumleapschools.org/news.aspx" target="_blank" rel="noreferrer">Read more <ArrowRight size={14} /></a></article><article><span>Admissions</span><h3>Plan your visit to Ikorodu</h3><p>Speak directly with the school team about year groups, pathways, and next steps.</p><a href="#admissions">Make an enquiry <ArrowRight size={14} /></a></article><article><span>Resources</span><h3>Keep families connected</h3><p>Quick access to the school portal, contact channels, and campus location.</p><a href="https://sms.quantumleapschools.org/" target="_blank" rel="noreferrer">Open portal <ArrowRight size={14} /></a></article></div></div></section>
      <section className="admissions container" id="admissions"><div className="admission-card"><div><div className="kicker light"><span /> Admissions</div><h2>Ready to take<br /><em>the next leap?</em></h2></div><div><p>Come and discover a school where your child can learn, grow, and become more of who they are meant to be.</p><button className="button button-white" onClick={openAdmissions}>Make an enquiry <ArrowRight size={16} /></button></div></div></section>
    </main>
    <footer className="footer"><div className="container footer-top"><Logo /><div className="footer-contact"><a href="mailto:quantumleap@yahoo.com">quantumleap@yahoo.com</a><a href="tel:+2348023153950">+234 802 315 3950</a><a href="https://wa.me/2348023153950" target="_blank" rel="noreferrer">WhatsApp admissions</a><a href="https://www.google.com/maps/search/?api=1&query=6-8+Salami+Solebo+Street+Igbo+Olowo+Ikorodu+Lagos" target="_blank" rel="noreferrer">Get directions</a><span>6–8 Salami Solebo Street, Igbo Olowo,<br />Oke-Oriya, Ikorodu, Lagos</span></div><div className="footer-links"><a href="#about">Our school</a><a href="#learning">Learning</a><a href="#admissions">Admissions</a><a href="https://sms.quantumleapschools.org/" target="_blank" rel="noreferrer">Portal</a></div></div><div className="container footer-bottom"><span>© 2026 Quantum Leap Schools</span><span>Learning with purpose · Growing with confidence</span></div></footer>
    {modal && <div className="modal-backdrop" onClick={() => setModal(false)}><div className="modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setModal(false)}><X size={18} /></button>{submitted ? <div className="success"><span><CircleCheck /></span><h2>Thank you.</h2><p>Your enquiry has been prepared for WhatsApp. The school team can continue the conversation there.</p><button className="button button-primary" onClick={() => setModal(false)}>Close</button></div> : <><div className="kicker"><span /> Admissions enquiry</div><h2>Let’s begin<br /><em>the conversation.</em></h2><form onSubmit={submitEnquiry}><label>Parent/guardian name<input name="name" required placeholder="Your name" /></label><label>Email or phone<input name="contact" required placeholder="How should we reach you?" /></label><label>Tell us about your enquiry<textarea name="enquiry" rows="4" required placeholder="Which year group are you enquiring about?" /></label><button className="button button-primary" type="submit">Continue to WhatsApp <ArrowRight size={16} /></button></form></>}</div></div>}
  </div>
}
